site_name: xverif
site_description: The documentation for the xverif python library.

repo_name: ghiggi/xverif
repo_url: https://github.com/ghiggi/xverif

nav:
  - Home: index.md
  - Reference:
    - xverif: api/xverif.md


theme:
  name: material

  features:
      - navigation.sections
      - toc.follow
      - header.autohide
      -
  logo: "assets/xverif_logo.svg"

  palette:
      - scheme: default
        primary: white
        accent: indigo
        toggle:
            icon: material/weather-night
            name: Switch to dark mode
      - scheme: slate
        primary: white
        accent: amber
        toggle:
            icon: material/weather-sunny
            name: Switch to light mode
  icon:
      repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: true
          rendering:
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: true
            members_order: source
            heading_level: 4
          options:
            docstring_style: "numpy"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css

extra_javascript:
  - scripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
